[package]
name = "sd-image-to-params"
version = "0.1.0"
edition = "2024"

[dependencies]
freya = "0.3.3"

walkdir = "2.5.0"
image = "0.25.6"
copypasta = "0.10.2"

ureq = "3.0.11"
serde_json = "1.0.140"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"